name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeating
        run: echo "Hello World!"
      - name: Print goodbye
        run: echo "Goodbye!"
